=== Kitananji/ERP/Projecte Net/MiniERP/bin/Debug/proveidors.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="proveidors" type="tipusProveidors"/>

  <xs:complexType name="tipusProveidors">
    <xs:sequence>
      <xs:element name="proveidor" type="tipusProveidor" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="tipusProveidor">
    <xs:sequence>
      <xs:element name="codi" type="tipusCodi"/>
      <xs:element name="nom" type ="xs:string"/>
      <xs:element name="adreça" type="xs:string"/>
      <xs:element name="poblacio" type="xs:string"/>
      <xs:element name="cp" type="tipusCp"/>
    </xs:sequence>
  </xs:complexType>

  <xs:simpleType name="tipusCodi">
    <xs:restriction base="xs:string">
      <xs:minLength value="1"/>
      <xs:maxLength value="4"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="tipusCp">
    <xs:restriction base="xs:string">
      <xs:pattern value="[0-9]{5}"/>
    </xs:restriction>
  </xs:simpleType>
  
</xs:schema>

=== Kitananji/ERP/Projecte Net/MiniERP/bin/Debug/proveidors.xml
<?xml version="1.0"?>
<proveidors xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="proveidors.xsd">
<proveidor>
	<codi>CP10</codi>
	<nom>Comercial paperera, materials doficina</nom>
	<adreça>Pol. Ind Mas Xirgu II</adreça>
	<poblacio>Girona</poblacio>
	<cp>17005</cp>
</proveidor>   
<proveidor>
	<codi>AB11</codi>
	<nom>Abacus Cooperativa</nom>
	<adreça>Carretera de Barcelona, 42-44</adreça>
	<poblacio>Girona</poblacio>
	<cp>17002</cp>
</proveidor>  
<proveidor>
	<codi>MSS1</codi>
	<nom>Massegur</nom>
	<adreça>Plaça Calvet i Rubalcava, 8</adreça>
	<poblacio>Girona</poblacio>
	<cp>17002</cp>
</proveidor>  
<proveidor>
	<codi>BBCP</codi>
	<nom>Bisbal Copy</nom>
	<adreça>C/Solidaritat, 40</adreça>
	<poblacio>La Bisbal dEmpordà</poblacio>
	<cp>17100</cp>
</proveidor>
<proveidor>
	<codi>NPP</codi>
	<nom>Neus Paper</nom>
	<adreça>Hortes, 17</adreça>
	<poblacio>Girona</poblacio>
	<cp>17010</cp>
</proveidor> 
</proveidors>
