=== Kitananji/ERP/Projecte/Projecte/MiniERP/bin/Debug/albara.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
   
  <xs:element name="albara" type="tipusAlbara" />

  <xs:complexType name="tipusAlbara" >
    <xs:sequence>
      <xs:element name="codiComanda" type="xs:integer"/>
      <xs:element name="data" type="xs:date"/>
      <xs:element name="articles" type="tipusArticles" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="tipusArticles">
    <xs:sequence>
      <xs:element name="article" type="tipusArticle" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="tipusArticle">
    <xs:sequence>
      <xs:element name="codi" type="tipusCodi"/>
      <xs:element name="quant" type="xs:integer"/>
      <xs:element name="preu" type="xs:integer"/>
    </xs:sequence>
  </xs:complexType>

  <xs:simpleType name="tipusCodi">
    <xs:restriction base="xs:string">
      <xs:minLength value="1"/>
      <xs:maxLength value="4"/>
    </xs:restriction>
  </xs:simpleType>
  
</xs:schema>

=== Kitananji/ERP/Projecte/MiniERP/bin/Debug/C2A1.xml
<?xml version="1.0" encoding="UTF-8"?>
<albara xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="albara.xsd">
  <codiComanda>1</codiComanda>
	<data>2015-05-27</data>	
	<articles>
		<article>
			<codi>AL01</codi>
			<quant>10</quant>
			<preu>77</preu>
		</article>
		<article>
			<codi>BK01</codi>
			<quant>30</quant>
			<preu>100</preu>
		</article>
		<article>
			<codi>BL06</codi>
			<quant>5</quant>
			<preu>250</preu>
		</article>
		<article>
			<codi>BL03</codi>
			<quant>10</quant>
			<preu>335</preu>
		</article>
	</articles>
</albara>
